### ISSUE TITLE
ToDo: Create PCB assembly documentation

### ISSUE THREAD

**Issue by pyr0ball** [pyr0ball/pyr0piezo#14]
Documents for PCB assembly are needed:

- [x] DXF simplified drawing of PCB components, front/back
- [x] component type/value list
- [ ] recommend assembly order
- [ ] PCB reflow thermal profile
- [ ] initial programming / bootloader install
- [x] firmware update procedure
- [x] Marlin Configuration Guide
- [ ] Repetier Configuration Guide
- [ ] RRFW Configuration Guide
- [x] Connection / hookup Guide - RAMPS
- [ ] Connection / hookup Guide - DuetWifi
- [x] Connection / hookup Guide - Creality OEM Board
- [ ] Connection / hookup Guide - MKS Series

**Comment by pyr0ball** [comment]
Added documentation in commits:
https://github.com/pyr0ball/pyr0piezo/commit/1d17a8dbc9c0e2c366f647574b28ad20244343db
https://github.com/pyr0ball/pyr0piezo/commit/e2399797b8cc4d5ed9e25f0dfded744ae7c06701

**Comment by pyr0ball** [comment]
Added PDF exports of all schematics used in boards that have been fabricated: https://github.com/pyr0ball/pyr0piezo/commit/c462b0a3dc5661c0f24a280ded8cff5d5fa49069
